"""Add is_confident column to emails

Revision ID: 3494a07fed0c
Revises: 9f243b0c00f9
Create Date: 2025-12-03 15:42:28.134892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3494a07fed0c'
down_revision: Union[str, Sequence[str], None] = '9f243b0c00f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('is_confident', sa.Boolean(), nullable=False, server_default=sa.false(), comment='Whether sufficient context was available for personalization'))
    op.alter_column('users', 'template_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Number of templates generated by this user',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'template_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='Number of templates generated by this user',
               existing_nullable=False)
    op.drop_column('emails', 'is_confident')
    # ### end Alembic commands ###
