"""Initial schema - users and emails tables

Revision ID: 4c1052b2c70b
Revises: 
Create Date: 2025-11-12 21:59:52.687960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1052b2c70b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='User ID from Supabase Auth'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address"),
    sa.Column('display_name', sa.String(length=255), nullable=True, comment="User's display name"),
    sa.Column('generation_count', sa.Integer(), nullable=False, comment='Number of emails generated by this user'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the user was created'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique email ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who generated this email'),
    sa.Column('recipient_name', sa.String(length=255), nullable=False, comment='Name of the email recipient'),
    sa.Column('recipient_interest', sa.String(length=500), nullable=False, comment='Research interest or topic for personalization'),
    sa.Column('email_message', sa.Text(), nullable=False, comment='The generated email content'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the email was generated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emails_created_at', 'emails', ['created_at'], unique=False, postgresql_using='btree')
    op.create_index('ix_emails_user_created', 'emails', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_emails_user_id'), 'emails', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_user_id'), table_name='emails')
    op.drop_index('ix_emails_user_created', table_name='emails')
    op.drop_index('ix_emails_created_at', table_name='emails', postgresql_using='btree')
    op.drop_table('emails')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
