"""add template type and metadata to emails

Revision ID: 5afd87136a29
Revises: 4c1052b2c70b
Create Date: 2025-11-14 00:34:40.381667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5afd87136a29'
down_revision: Union[str, Sequence[str], None] = '4c1052b2c70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    template_enum = postgresql.ENUM(
        'research', 'book', 'general',
        name='template_type_enum'
    )
    template_enum.create(op.get_bind())  
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('template_type', template_enum, nullable=False, comment='Pipeline template classification'))
    op.add_column('emails', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Structured generation metadata (papers, sources, timings)'))
    op.create_index(op.f('ix_emails_template_type'), 'emails', ['template_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_emails_template_type'), table_name='emails')
    op.drop_column('emails', 'metadata')
    op.drop_column('emails', 'template_type')
    # ### end Alembic commands ###
