"""Add email_template column to users

Revision ID: 86348643ad0b
Revises: ea71a873bb8e
Create Date: 2026-01-13 00:46:16.219054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86348643ad0b'
down_revision: Union[str, Sequence[str], None] = 'ea71a873bb8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_template', sa.Text(), nullable=True, comment="User's cold email template for generation"))
    # Note: Alembic sometimes incorrectly detects changes to ix_users_email during autogenerate.
    # We intentionally do NOT touch the existing (unique) email index in this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_template')
    # ### end Alembic commands ###
