"""add templates table and template_count to users

Revision ID: 9f243b0c00f9
Revises: 5afd87136a29
Create Date: 2025-11-25 12:21:29.294305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f243b0c00f9'
down_revision: Union[str, Sequence[str], None] = '5afd87136a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique template ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who generated this template'),
    sa.Column('pdf_url', sa.String(length=500), nullable=False, comment='Supabase Storage URL for resume PDF'),
    sa.Column('template_text', sa.Text(), nullable=False, comment='Generated template content'),
    sa.Column('user_instructions', sa.Text(), nullable=False, comment='User guidance for template generation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the template was generated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_templates_created_at', 'templates', ['created_at'], unique=False, postgresql_using='btree')
    op.create_index('ix_templates_user_created', 'templates', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_templates_user_id', 'templates', ['user_id'], unique=False)
    op.add_column('users', sa.Column('template_count', sa.Integer(), nullable=False, server_default='0', comment='Number of templates generated by this user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'template_count')
    op.drop_index('ix_templates_user_id', table_name='templates')
    op.drop_index('ix_templates_user_created', table_name='templates')
    op.drop_index('ix_templates_created_at', table_name='templates', postgresql_using='btree')
    op.drop_table('templates')
    # ### end Alembic commands ###
