"""Add queue_items table

Revision ID: bbddd04b993d
Revises: a0cdf47631c6
Create Date: 2026-01-13 17:02:11.087590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbddd04b993d'
down_revision: Union[str, Sequence[str], None] = 'a0cdf47631c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique queue item ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who submitted this queue item'),
    sa.Column('recipient_name', sa.String(length=255), nullable=False, comment='Name of the email recipient'),
    sa.Column('recipient_interest', sa.Text(), nullable=False, comment='Research interest for personalization'),
    sa.Column('email_template', sa.Text(), nullable=False, comment='Email template snapshot at submission time'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Current status: pending, processing, completed, failed'),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True, comment='Celery task ID for status polling fallback'),
    sa.Column('email_id', sa.UUID(), nullable=True, comment='Generated email ID on successful completion'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details if status is failed'),
    sa.Column('current_step', sa.String(length=50), nullable=True, comment='Current pipeline step: template_parser, web_scraper, arxiv_helper, email_composer'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the item was submitted to queue'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='When processing started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When processing completed or failed'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_items_created_at'), 'queue_items', ['created_at'], unique=False)
    op.create_index('ix_queue_items_status', 'queue_items', ['status'], unique=False)
    op.create_index('ix_queue_items_user_id', 'queue_items', ['user_id'], unique=False)
    op.create_index('ix_queue_items_user_status', 'queue_items', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_queue_items_user_status', table_name='queue_items')
    op.drop_index('ix_queue_items_user_id', table_name='queue_items')
    op.drop_index('ix_queue_items_status', table_name='queue_items')
    op.drop_index(op.f('ix_queue_items_created_at'), table_name='queue_items')
    op.drop_table('queue_items')
    # ### end Alembic commands ###
