"""add onboarded column to users

Revision ID: ea71a873bb8e
Revises: fa538ab74d2b
Create Date: 2026-01-13 00:09:06.883834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea71a873bb8e'
down_revision: Union[str, Sequence[str], None] = 'fa538ab74d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarded', sa.Boolean(), nullable=False, server_default='false', comment='Whether the user has completed the onboarding welcome screen'))
    # Note: Alembic incorrectly detected index change - email index should remain unique
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarded')
    # ### end Alembic commands ###
