"""add displayed column to emails for soft delete

Revision ID: fa538ab74d2b
Revises: 3494a07fed0c
Create Date: 2026-01-01 18:23:19.592207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa538ab74d2b'
down_revision: Union[str, Sequence[str], None] = '3494a07fed0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('displayed', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment="Whether email is visible in user's history (soft delete)"))
    op.alter_column('emails', 'is_confident',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Whether sufficient context was available for personalization',
               existing_nullable=False)
    op.create_index(op.f('ix_emails_displayed'), 'emails', ['displayed'], unique=False)
    op.create_index('ix_emails_user_displayed', 'emails', ['user_id', 'displayed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emails_user_displayed', table_name='emails')
    op.drop_index(op.f('ix_emails_displayed'), table_name='emails')
    op.alter_column('emails', 'is_confident',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Whether sufficient context was available for personalization',
               existing_nullable=False)
    op.drop_column('emails', 'displayed')
    # ### end Alembic commands ###
