"""User model for authenticated users linked to Supabase auth."""

from sqlalchemy import Column, String, Integer, DateTime, Index, Boolean
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from database.base import Base


class User(Base):
    """User account linked to Supabase auth. Tracks email generation usage and owns Email/Template records."""

    __tablename__ = "users"

    # Primary Key - matches Supabase auth.users UUID
    id = Column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        nullable=False,
        comment="User ID from Supabase Auth"
    )

    # User Information
    email = Column(
        String(255),
        nullable=False,
        unique=True,
        index=True,
        comment="User's email address"
    )

    display_name = Column(
        String(255),
        nullable=True,
        comment="User's display name"
    )

    # Usage Tracking
    generation_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of emails generated by this user"
    )

    template_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of templates generated by this user"
    )

    # Onboarding Status
    onboarded = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="Whether the user has completed the onboarding welcome screen"
    )

    # Timestamps
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="When the user was created"
    )

    # Relationships
    emails = relationship(
        "Email",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="dynamic"
    )

    templates = relationship(
        "Template",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="dynamic"
    )

    # Indexes
    __table_args__ = (
        Index('ix_users_email', 'email'),
        Index('ix_users_created_at', 'created_at'),
    )

    def __repr__(self) -> str:
        """String representation of User model."""
        return f"<User(id={self.id}, email='{self.email}', generation_count={self.generation_count})>"
